version: '3.8'
services:
jira:
image: YourImageName:tag
container_name: jira
ports:
- "8080:8080" # Maps host port 8080 to container port 8080
depends_on:
- postgres
environment:
- ATL_JDBC_URL=jdbc:postgresql://#your url postgres/jiradb?tcpKeepAlive=true&socketTimeout=240
- ATL_JDBC_USER=jirauser
- ATL_JDBC_PASSWORD=jirapassword
# Ensure tcpKeepAlive is set to true to avoid the warning
volumes:
- jira_data:/var/atlassian/application-data/jira
networks:
- jira-net

postgres:
image: postgres:13
container_name: postgres
ports:
- '5432:5432' # Maps host port 5433 to container port 5432
environment:
- POSTGRES_DB=jiradb
- POSTGRES_USER=jirauser
- POSTGRES_PASSWORD=jirapassword
volumes:
- postgres_data:/var/lib/postgresql/data
networks:
- jira-net

volumes:
jira_data:
postgres_data:

networks:
jira-net:
driver: bridge
